### ISSUE TITLE
Make sure that a property is defined in the ontology

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#242] opened 2016-08-25 11:50 UTC
When you define a cardinality for a property on a resource class, we do not make sure that this property is actually defined.

Can we make the consistency checker check that every reference to a property can be resolved?

**Comment by benjamingeer** [comment] 2016-09-13 09:09
I tried writing a consistency rule for this:

```
// If there's a cardinality on a property, the property must be defined.
Consistency: cardinality_property_exists
    r <owl:onProperty> p
    ------------------------------------
    p x y
```

It works if it's the only custom rule in the PIE file. But if I add it to our existing rules, it never seems to trigger. I've asked Ontotext about it.

**Comment by benjamingeer** [comment] 2016-09-16 07:09
Ontotext says my rule doesn't work because of a GraphDB bug, which will be fixed in GraphDB 7.2.1.

**Comment by tobiasschweizer** [comment] 2016-09-16 07:14
I am happy that they have bugs, too ...

**Comment by tobiasschweizer** [comment] 2016-09-30 13:01
Actually there are use cases like the extended search where we would want to use properties that are not defined in our ontology and thus not in the triplestore. This is because we need to support external standard vocabularies.

For Dublin Core, we provided a wrapper in knora-base. So we redefined the dc in the knora-base way. For example, a property needs to have a `knora-base:objectClassConstraint`, i.e. a value type. Otherwise the extended search does not work because the responder checks for valid combinations between properties and comparison operators. And in order to do so, it needs its `knora-base:objectClassConstraint`.

So we cannot support any searches for properties that are not defined somewhere in the triplestore. Moreover, a property must always have the same `knora-base:objectClassConstraint`. So a `dc:creator` must be either a text value or a resource pointer in all the projects.
If someone searches for `dc:creator`, we must get its value type without any further context information.

**Comment by benjamingeer** [comment] 2016-09-30 13:05
Could we change the way the extended search works, so that it would not need to know the property's `objectClassConstrant`? In other words, if you say "find me a `dc:title` with this text value", could it just look for instances of `dc:title` that actually point to text values, and ignore instances of `dc:title` that point to resources?

**Comment by tobiasschweizer** [comment] 2016-09-30 13:09
At the moment an extended search like this is possible (only on branch `wip/beol-onto` since we changed the SPAQRL):

<http://localhost:3333/v1/search/?searchtype=extended&property_id=http%3A%2F%2Fwww.knora.org%2Fontology%2Fdc%23title&compop=LIKE&searchval=Narr&show_nrows=25&start_at=0>

But `http://www.knora.org/ontology/dc#title` should actually say: `http://purl.org/dc/elements/1.1/title`. No one will search for the first one.

**Comment by tobiasschweizer** [comment] 2016-09-30 13:12
> Could we change the way the extended search works, so that it would not need to know the property's objectClassConstrant? In other words, if you say "find me a dc:title with this text value", could it just look for instances of dc:title that actually point to text values, and ignore instances of dc:title that point to resources?

This would not be supported by the GUI at all. How should we determine the list of possible comparison operators?

Lukas proposed to decide on a static `objectClassConstraint`. So each object of dc:creator or any subproperty of it would have to be a subclass of a kb:resource. Existing text value creators would have to be remodelled to resources.

**Comment by tobiasschweizer** [comment] 2016-09-30 13:18
Ah, do you mean in the GUI you specifiy that you are looking for dc:title texts?

**Comment by benjamingeer** [comment] 2016-09-30 13:20
> How should we determine the list of possible comparison operators?

The possible comparison operators could be based on what the user actually inputs in the GUI. If the user says they want to look for a text value, then we could allow the comparison operators that are valid for text values. If they say they want to look for a resource, we could allow the comparison operators that are valid for resources.

> Ah, do you mean in the GUI you specifiy that you are looking for dc:title texts?

Yes. Let them select `http://purl.org/dc/elements/1.1/title` as the property, and then let them choose the type of object they're interested in. Then you can determine which operators are relevant.

**Comment by mrivoal** [comment] 2016-09-30 13:30
But then Knora would be much more constraigning that DC ontology itself if `dc:creator` had a `objectclassContraint` on `knora-base:Resource`.

I am not sure I will follow you on this. In my opinion, modeling in Knora (and for Salsah) already brings a lot of constraints. Knora shouldn't had constraints that do not exist in the other ontologies (but I am not sure I fully undestand what you mean/want).

Plus, searching for a dc:creator + the type of object you want to search in implies a very good understanding of the data model. I am not sure the average Salsah user will have enough knowledge to build the query.

**Comment by benjamingeer** [comment] 2016-09-30 13:37
@mrivoal So what should we do? The problem is that `dc:creator` doesn't provide any constraints at all. So we have two options:

1. Constrain `dc:creator` in a Knora-specific way, and require users to respect that constraint.
2. Leave `dc:creator` unconstrained, and allow users to search for any kind of object they think might be in the repository.

I agree with you that Knora shouldn't add constraints to existing ontologies, so we can't do (1). Hence it seems to me that (2) is the only option.

If the user doesn't know what kind of object might be in the respository, then I think they shouldn't use `dc:creator` in a search query. Instead, they should use a project-specific subproperty of `dc:creator`, which would have an `objectClassConstraint`, so they wouldn't have to guess what kind of object to look for.

**Comment by mrivoal** [comment] 2016-09-30 13:47
Maybe (2) is the best option. If project-specific ontologies can still define their own intrepretation of `dc:creator` by creating a subproperty of `dc:creator`, I guess it is fine.

**Comment by tobiasschweizer** [comment] 2016-10-07 08:02
Speaking about third party ontologies: I had a look at the GND/IAF records maintained by the German National Library. The GND/IAF identifiers can be resolved as Turtle: <http://d-nb.info/gnd/117589136/about/lds>

And in there, you also find: 

```
<http://d-nb.info/gnd/117589136> a gndo:DifferentiatedPerson ;
	foaf:page <http://de.wikipedia.org/wiki/Johann_II._Bernoulli> ;
	owl:sameAs <http://dbpedia.org/resource/Johann_II_Bernoulli> , <http://viaf.org/viaf/56879472> .
```

This means you can go to the dbpedia SPARQL endpoint and query for <http://dbpedia.org/resource/Johann_II_Bernoulli>.

How shall we handle this in Knora? I think we should not just output a URI but also resolve it and display the data in the GUI as well.

**Comment by benjamingeer** [comment] 2016-10-07 09:07
> How shall we handle this in Knora?

There are a couple of things going on here:

1. Supporting `owl:sameAs`, so that IRIs have synonyms that can be used interchangeably.
2. Running an HTTP service that resolves IRIs directly as URLs.

About (1): if you want the Knora API to accept `http://dbpedia.org/resource/Johann_II_Bernoulli` as synonymous with some IRI `http://data.knora.org/xyz` representing the same person, every SPARQL query would need either to use inference or to be more complex. As a simpler alternative, we could offer an API operation called something like `getKnoraIri`, which would accept an external IRI and return its Knora equivalent, if any.

About (2): We can't run an HTTP service that resolves `http://dbpedia.org/resource/Johann_II_Bernoulli`, because we don't operate the domain `dbpedia.org`. We can run a service that resolves `http://data.knora.org/xyz`, though. The recommended way to do this is with [content negotation](https://www.w3.org/TR/swbp-vocab-pub/#negotiation), so the client can specify whether it wants RDF data or a GUI display.

**Comment by tobiasschweizer** [comment] 2016-10-07 15:27
current status on the `labels` branch: one can define subproperties and subclasses of non Knora properties and classes without the ontology responder crashing, i.e trying to get information about them in the triplestore itself (because they are not subject of any statements).

Instead of trying to get standard vocabularies working inside Knora, we rather dump our data to a simplified structure supporting basic standard vocabularies (everything becomes a literal). Always use the most generic property of resource class available. Have a look at the Open Annotation Collaboration's model.

**Comment by benjamingeer** [comment] 2016-10-07 15:41
This is similar to what we're doing with TEI/XML: we store your text with standoff markup, but we can generate TEI/XML if you need it.

**Comment by tobiasschweizer** [comment] 2016-10-07 17:38
Actually, the namespace `dcterms` specifies ranges for properties (<http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#H2>): 
> Properties in the /terms/ namespace:
>Term Name:    creator 
>URI:	http://purl.org/dc/terms/creator
>Label:	Creator
>Definition:	An entity primarily responsible for making the resource.
>Comment:	Examples of a Creator include a person, an organization, or a service.
>Type of Term:	Property
>Refines:	http://purl.org/dc/elements/1.1/creator
>Refines:	http://purl.org/dc/terms/contributor
>Has Range:	http://purl.org/dc/terms/Agent
>Version:	http://dublincore.org/usage/terms/history/#creatorT-002
>EquivalentProperty:	http://xmlns.com/foaf/0.1/maker

So the object constraint of to a resource of the class `dcterms:Agent` or any subclass of it in Knora would be DC compliant: 
> 	Has Range:	 : A Class of which a value described by the term is an Instance.
(<http://dublincore.org/documents/2012/06/14/dcmi-terms/>)

So could we just support `dcterms`?

**Comment by tobiasschweizer** [comment] 2016-10-07 17:43
> Question: What is the difference between dc:creator and dcterms:creator, and why have the fifteen elements of the Dublin Core been declared using two separate namespaces? 
> [...] As RDF matured, these properties were criticized in Semantic Web circles for being underspecified and thus ambiguous. For example, was dc:creator intended to refer to the creator of a resource (an object) or to the name of the creator (a string)?
(<http://wiki.dublincore.org/index.php/FAQ/DC_and_DCTERMS_Namespaces>)

**Comment by benjamingeer** [comment] 2016-10-07 19:11
OK, but what is a `dcterms:Agent`? The definition appears to be empty:

http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#Agent

Also, `dcterms:title` still has a range of `rdfs:Literal`:

http://dublincore.org/documents/2012/06/14/dcmi-terms/?v=terms#terms-title

**Comment by benjamingeer** [comment] 2016-10-10 12:19
It looks like the best we can do is:

* Load standard ontologies like `dcterms` and `foaf` into the triplestore, so we don't have undefined properties, thus allowing the consistency checker to report an undefined property as an error.
* Use standard properties/classes as superproperties/superclasses in Knora ontologies.
* Support using standard, non-Knora classes (like foaf:Person) as resource type restrictions in searches.
* Don't support using standard, non-Knora properties (like `dcterms:title`) in searches.
* If a project wants searchable data using standard properties, export the data to a simplified format that can be searched directly in SPARQL.

**Comment by benjamingeer** [comment] 2016-10-10 12:22
We can also keep `knora-dc`, and add `knora-dcterms`, with classes like `Agent`, which can be used across Knora projects.

**Comment by benjamingeer** [comment] 2016-11-16 15:14
> Ontotext says my rule doesn't work because of a GraphDB bug, which will be fixed in GraphDB 7.2.1.

The fix to this bug introduced another bug. Ontotext says this should be resolved in Ontotext 8.0, due in a few weeks.

**Comment by tobiasschweizer** [comment] 2016-11-17 07:47
Which version of graphdb should we use meanwhile? I am still using 7.1.0.

**Comment by benjamingeer** [comment] 2016-11-17 08:07
We have to stay with 7.1.0 for now, because a bug in 7.2 breaks our consistency checking.

**Comment by subotic** [comment] 2016-11-17 08:09
They are changing their versioning strategy? Every few months a new major release?

**Comment by benjamingeer** [comment] 2016-11-17 08:11
I guess it's because version 8 will be based on Eclipse RDF4J, the successor to Sesame.

**Closed** 2018-02-07 12:42 UTC
Labels: enhancement
