### ISSUE TITLE
Bulk import: transform entities before saving them as a simple string

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#1105] opened 2018-12-06 13:49 UTC
If a simple string without markup is submitted using the bulk import, XML standard entities should not be saved directly in the triplestore. 

`&amp;` should be saved as `&`, the same goes for `<`, `>` etc. https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

**Comment by SepidehAlassi** [comment] 2018-12-06 14:08
@tobiasschweizer this is not a problem of bulk import or saving in triplestore. When a user creates an xml, he/she should be able to validate it before the import. If there are & or < or > in xml then xml is not valid. The user will then get lots of errors because of these characters when he tries to validate with xsd schemas. Consequently, the user will skip validating or will ignore checking all the thrown errors. This completely ruins the concept of validation of xml before import! @benjamingeer  what do you think?

**Comment by tobiasschweizer** [comment] 2018-12-06 14:09
No, this is not what I mean. The xml validation should stay how it is. But we have to transform the entities before storing them.

**Comment by SepidehAlassi** [comment] 2018-12-06 14:17
Ok, I see. But the problem is not just with these three characters. For example, There are many other characters in LEOO xmls which are converted to HTML characters. for example `&apos;`  or many others for special greek characters. We can not add all the list of all possible HTML characters to be converted back to string for saving in triplestore.

**Comment by tobiasschweizer** [comment] 2018-12-06 14:19
I assume it is just the predefined XML entities https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML

If an entity is undefined, the XML processor would throw an error. I will look at the data in the triplestore tomorrow just to be sure.

**Comment by tobiasschweizer** [comment] 2018-12-06 14:53
I think `https://github.com/dhlab-basel/Knora/blob/develop/webapi/src/main/scala/org/knora/webapi/util/standoff/XMLToStandoffUtil.scala` deals with these problems already.

**Comment by tobiasschweizer** [comment] 2018-12-07 14:03
I checked the triplestore for `Mémoires de l&apos;Académie Royale des Sciences` (beol-id: mem_paris)

```
http://www.knora.org/ontology/knora-base#valueHasString "Mémoires de l&apos;Académie Royale des Sciences"
```

So the entity got into the triplestore. I will check if I can reproduce that in a test scenario.

**Comment by tobiasschweizer** [comment] 2018-12-07 14:53
@SepidehAlassi I cannot reproduce this using the bulk import. I do not understand how entities end up in the triplestore. 

Could you please check the input XML for `Mémoires de l&apos;Académie Royale des Sciences` (beol-id: mem_paris)? Are entities double encoded in XML or something like that?

**Comment by SepidehAlassi** [comment] 2018-12-07 15:03
@tobiasschweizer here is the corresponding XML element

`<biblio:Journal id="mem_berlin">
		<biblio:hasName>Mémoires de l&apos;Académie Royale des Sciences et Belles-Lettres</biblio:hasName>
	</biblio:Journal>`

**Comment by SepidehAlassi** [comment] 2018-12-07 15:06
@tobiasschweizer Here is the corresponding XML element:
 `<biblio:Journal id="mem_berlin">
    <knoraXmlImport:label>Mémoires de l'Académie Royale des Sciences et Belles-Lettres</knoraXmlImport:label>
    <biblio:p0801-beol__beolIDs knoraType="richtext_value">mem_berlin</biblio:p0801-beol__beolIDs>
    <biblio:p0801-beol__mentionedIn knoraType="richtext_value">LEOO IVA4</biblio:p0801-beol__mentionedIn>
    <biblio:hasName knoraType="richtext_value">Mémoires de l&amp;apos;Académie Royale des Sciences et Belles-Lettres</biblio:hasName>
  </biblio:Journal>`

**Comment by tobiasschweizer** [comment] 2018-12-07 15:20
This works for me: `Mémoires de l'Académie Royale des Sciences et Belles-Lettres` is saved to the triplestore. 

I have no idea why the beol data contains `Mémoires de l&apos;Académie Royale des Sciences `

**Comment by SepidehAlassi** [comment] 2018-12-07 15:32
@tobiasschweizer I don't know either. I will look into this next week.

**Comment by tobiasschweizer** [comment] 2018-12-07 15:38
My guess would be double escaping: `&apos;` -> `&amp;apos;`

**Comment by tobiasschweizer** [comment] 2018-12-11 17:17
@SepidehAlassi Did you find out why `&apos;` was saved to the triplestore?
Unfortunately, I was unable to reproduce the problem. The only thing I can imagine is that entities got encoded twice. Maybe before sending the XML to Knora.

**Comment by SepidehAlassi** [comment] 2018-12-12 14:58
@tobiasschweizer I am looking into this today

**Comment by SepidehAlassi** [comment] 2018-12-12 15:59
@tobiasschweizer yes you are right.  During the import, my code was double escaping the characters. I fixed the bug, it is not a Knora issue. We can close this one

**Closed** 2018-12-12 15:59 UTC
Labels: API v1
