### ISSUE TITLE
Option to not retrieve ForbiddenResource 

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1016] opened 2018-10-23 10:50 UTC
is it possible to optionally not return `ForbiddenResource` when we use gravsearch API and keep of course the count and the page size consistent ? (I mean completely ignore `ForbiddenResource`)

In Salsah I can admit that to provide the information that other resources are existing but not accessible is important, but in a dedicated web app, we finally use permissions to really hide resources to some users, so we have to post-filter those `ForbiddenResource`, that is re-invent a page system to cache incomplete page, get elements of the next pages to complete current page and so on :| is it feasable directly in Knora ?

p.s. : maybe I could filter `ForbiddenResource` by excluding them in the gravsearch query ?

**Comment by tobiasschweizer** [comment] 2018-10-23 12:57
`ForbiddenResource` is a placeholder for a resource and ensures that search results are returned in a deterministic way which is important for paging.  If we want to change this, we would have to handle paging in a different way (prequery). 

I can surely think about this when I do the refactoring of Gravsearch (#926), but I think that this would require quite a big design change. We would probably have to keep track of an internal and an external offset when doing paging. The external offset would differ from the internal if the client has insufficient permissions.

But I get your point and will think about it!

**Comment by gfoo** [comment] 2018-12-07 09:59
Well, don't remove `ForbiddenResource` if you don't keep page's sizes constant, it is not _enough_ interesting for me anyway :) Not a big deal for me to ignore `ForbiddenResource`, the real problem is the page size in fact.

n.b. : I don't use the search component but directly the gravsearch endpoint

**Comment by benjamingeer** [comment] 2018-12-07 10:01
> I don't use the search component but directly the gravsearch endpoint

I think there could still be some kind of client-side component that would handle this extra work. Are you using Angular?

**Comment by gfoo** [comment] 2018-12-07 10:08
yes and I'm not against to do that on client side (I will have a look next week), was just logical for me to implement that on server side (but I really don't know your technical constraints).

**Comment by benjamingeer** [comment] 2018-12-07 10:11
> was just logical for me to implement that on server side (but I really don't know your technical constraints)

The problem is this:

Suppose you ask the server for page 1, and it thinks, "Aha, page 1 is incomplete, I will return some results from page 2 as well."

So you get a full "page 1". But then you request page 2. The problem is that the server has no way of knowing what results it already returned for page 1. So you will get the same page 2 results again.

That's why I think this has to be done in the client.

**Comment by tobiasschweizer** [comment] 2018-12-07 10:41
How it works in the client in https://github.com/dhlab-basel/beol:

- get the overall amount of hits by doing a count query
- calculate the max. offset (max. pagesize is known, e.g., 25)
- as long as the max. offset is not reached, display a button to query for more results

I think the server optionally could just not return `ForbiddenResource`, and the client would still know the max. offset. As long as the max. offset is not reached, the client has to keep asking to get all results. Also if you get an empty page, there could still be more results.

Would that make sense? Adding this option (default would be false) would not break any existing client code.

**Comment by tobiasschweizer** [comment] 2018-12-07 11:58
> Wouldn't it be easier for the client if the server just returned a boolean, indicating whether the max. page size was reached?

I think that would work too. So you could get no results for a specific offset and still know that there is more to go for.

Whatever we do, it has to be coordinated with Knora UI and apps that use its modules.

**Comment by gfoo** [comment] 2018-12-07 13:18
@tobiasschweizer I've seen what you have done in beol, are you talking about the infinite scroll ? 

@benjamingeer ok, I think I understand a little bit, are you saying that you depend on the page returned by the triplestore ? and at this point the page already contains the `ForbiddenResource` and finally it is too late ?

What I do today (with pages containing `ForbiddenResource`):
- get count
- get first page (page size = size of the current page and then compute the page count)
- then I can get the page I want using gravsearch offset.
But now, I'm not sure if what I have done is correct :| What happened if the data change on the server ? And I probably misunderstood the gravsearch offset, that is not a page index...

For example how to deal with Knora to use this kind of Angular component, can we really use this with Knora unless we get all the data before, or at least all IRIs of a query ? https://material.angular.io/components/table/overview#pagination

A straightforward solution could be to provide the IRI list of a query instead of a count and then I fill each page by querying them (using gravsearch with BIND)

**Comment by gfoo** [comment] 2018-12-07 13:32
this is what I have to implement for example from the existing Lumières.Lausanne web site, 319 pages:
[http://lumieres.unil.ch/chercher/?q=*]( http://lumieres.unil.ch/chercher/?q=*)

**Comment by benjamingeer** [comment] 2018-12-07 13:44
@gfoo 

> ok, I think I understand a little bit, are you saying that you depend on the page returned by the triplestore ?

Yes.

> and at this point the page already contains the ForbiddenResource and finally it is too late ?

The triplestore doesn't return `ForbiddenResource`, because Knora's permission logic can't be implemented efficiently in SPARQL. Instead, it works like this:

Suppose the page size is 10. This gives the following correspondence between Gravsearch pages and triplestore results:

| Gravsearch page number | Triplestore result rows |
|------------------------|:-----------------------:|
| 0                      |           0-9           |
| 1                      |          10-19          |
| 2                      |          20-29          |

Suppose you ask for Gravsearch page 2. Knora does a `SELECT` query, asking the triplestore for result rows 20-29 (`OFFSET 20 LIMIT 10`). The triplestore returns those 10 rows. Each row represents a resource that matched your search criteria. Now Knora looks at each of those resources, and decides whether you have permission to view it. If Knora decides that you don't have permission to see a resource, it replaces that resource with `ForbiddenResource` in its response to you.

This way, Knora does not store any information about your query as you are paging through the results. It relies on the triplestore to do the paging. Knora only needs to filter the 10 resources in each page, according to your permissions.

It's designed this way so that it can scale: the triplestore only returns a small amount of data to Knora (one page) per request, and Knora only returns that small amount of data (or less) to the client. This way, each search request is processed quickly, and Knora can handle many concurrent search requests.

> What happened if the data change on the server ? 

That can happen at any time. It could happen:

* Between the time when you do the count query and the time when you start getting the results.
* Between getting one page and getting the next page.

> And I probably misunderstood the gravsearch offset, that is not a page index...

It's a page index, which Knora translates into a SPARQL `OFFSET` when it queries the triplestore.

> For example how to deal with Knora to use this kind of Angular component

@tobiasschweizer and @flavens are the experts on this.

> A straightforward solution could be to provide the IRI list of a query instead of a count and then I fill each page by querying them (using gravsearch with BIND)

That wouldn't scale. Suppose your query matched 100 million resources? We can't return 100 million IRIs in an API response.

**Comment by tobiasschweizer** [comment] 2018-12-07 13:47
> I've seen what you have done in beol, are you talking about the infinite scroll ?

We do not use the scroll event at the moment, but the principle is the same. When the user does a search, the first page is displayed. More pages can be fetched by clicking on a button. The button is disabled once the max. offset has been reached.

**Comment by benjamingeer** [comment] 2018-12-07 14:06
@gfoo Also, in case this wasn't clear enough: the triplestore doesn't store any information about your query, either. Every time you ask for another page, the triplestore runs the same SPARQL query again, and skips the first N rows to get the page you asked for.

**Comment by gfoo** [comment] 2018-12-07 14:46
@tobiasschweizer ok, this is what I was thinking about, the name `infinite scroll` is not correct, sorry. Your UI context is a search result and it makes sense to provide only one button to get next results. Maybe the Lumières.Lausanne web site is not really well designed from UX point of view... Why finally should I provide a direct link button to the 319 page ? How stupid I am :^)

@benjamingeer But Knora could store query's id and return it to the client. This is maybe what we call a _cursor_ in RDBMS ? But yeah, we are out of this issue :) Really thanks for the explanations !

I think I will choose the @tobiasschweizer solution for typical search page results for which, by def, we cannot make any assumptions about the result size. For other pages like this one, have a look to the `Ecrits non publiés`: http://lumieres.unil.ch/fiches/bio/269/, or this one : http://lumieres.unil.ch/chercher/person/list, I can probably make the assumption that the result won't be huge and get all the data.

About this issue, I don't really know if it is important to implement the option to filter `ForbiddenResource`, I can easily do that on the client side because I finally won't implement a full page per page system. If it is just a requirement for me, we can let this issue in stand by for now.

**Comment by benjamingeer** [comment] 2018-12-07 14:50
> But Knora could store query's id and return it to the client. This is maybe what we call a cursor in RDBMS ?

There are no cursors or query IDs in SPARQL.

> Really thanks for the explanations !

No problem. We should add these explanations to the docs, too.

**Comment by gfoo** [comment] 2018-12-07 15:31
Infinite scroll is for me just an UI enhancement, you don't have to click on the "Load more", the scroll down to the bottom event click for us !

**Comment by tobiasschweizer** [comment] 2018-12-07 15:40
> Infinite scroll is for me just an UI enhancement, you don't have to click on the "Load more", the scroll down to the bottom event click for us !

Yes, absolutely!

**Comment by benjamingeer** [comment] 2019-01-08 16:52
Closing this because it seems to be resolved. Please reopen it, or open another issue, if you need more help.

**Closed by benjamingeer** 2019-01-08 16:52 UTC
Labels: Gravsearch, enhancement
