### ISSUE TITLE
support lists

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#275] opened 2016-09-29 09:28 UTC
Support RDF sequence for Knora and Salsah.
Ex: for list of Authors, we would like to have order specified, as first author, second, etc.

**Comment by benjamingeer** [comment] 2016-09-29 10:00
This is already implemented, using the property `knora-base:valueHasOrder`. See _The Knora Base Ontology_, section 2.3.1. This was designed to be simpler than the cumbersome RDF list syntax. If a resource property has more than one value, they're currently numbered in the order in which they're added. This order is then used to sort values when they are returned by API operations. A future version of the API could make it possible to change the order of the values.

**Comment by tobiasschweizer** [comment] 2016-09-29 10:28
But what happens if you delete the first value? Does the second author become the first author?

**Comment by benjamingeer** [comment] 2016-09-29 10:37
Yes. The `valueHasOrder` of the second author will not change, and doesn't need to, because it is only a relative position, not an absolute one. As the documentation says:

> These integers will not necessarily start at any particular number, and will not necessarily be consecutive.

**Comment by tobiasschweizer** [comment] 2016-09-29 10:57
Ok, but will the GUI support that? Once you have deleted the first value, will one be able to recreate a first value that comes before all the others?

**Comment by benjamingeer** [comment] 2016-09-29 11:23
As far as I know, the current GUI doesn't provide a way to do that, and neither does the current API. When you add a new value for a property, currently it always becomes the last value for the property. Do we need to be able to do this now, or can it wait till API v2?

**Comment by tobiasschweizer** [comment] 2016-09-29 11:28
The basic question is how we are going to support rdf sequence which is an **ordered** collection (in contrast to a bag): https://www.w3.org/TR/rdf-schema/#ch_seq

**Comment by benjamingeer** [comment] 2016-09-29 11:53
Why do you want an RDF sequence? It seems to me that `valueHasOrder` already meets the requirement for an ordered sequence.

**Comment by tobiasschweizer** [comment] 2016-09-29 13:06
Our problem is that it is a linking property, not an ordinary value.

So our list consists of authors is actually a series of person IRIs. Where would the `valueHasOrder` go? In the reification statement?

**Comment by benjamingeer** [comment] 2016-10-07 09:10
Can I close this issue?

**Comment by benjamingeer** [comment] 2016-10-07 09:13
> Where would the `valueHasOrder` go? In the reification statement?

Yes, a `LinkValue` already has a `valueHasOrder`, like any other value.

**Comment by tobiasschweizer** [comment] 2016-10-07 13:24
But we do not have an API operation that would allow the insertion of a value *between* exsiting values or reirder them.

**Comment by benjamingeer** [comment] 2016-10-07 13:31
> But we do not have an API operation that would allow the insertion of a value between exsiting values or reorder them.

That's right. That's why I asked you:

> Do we need to be able to do this now, or can it wait till API v2?

**Comment by tobiasschweizer** [comment] 2016-10-07 13:37
It can wait until V2. I added a section to our document in our local git.

**Closed by tobiasschweizer** 2016-10-07 13:37 UTC
Labels: enhancement
