### ISSUE TITLE
Preview of search results (searchinfowin)

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Knora#317] opened 2016-11-11 11:57 UTC
While trying to preview search results, here is what we get (raw JSON instead of object rendering):

![capture d ecran 2016-11-11 a 12 51 19](https://cloud.githubusercontent.com/assets/17294309/20214400/443437a2-a80e-11e6-80ea-e48ff263bece.png)

**Comment by benjamingeer** [comment] 2016-11-11 12:01
Duplicate of #314.

**Closed by benjamingeer** 2016-11-11 12:01 UTC
Labels: bug, duplicate, frontend (salsah)
