### ISSUE TITLE
API returns user data without authentication

### ISSUE THREAD

**Issue by andreas-aeschlimann** [dhlab-basel/Knora#1207] opened 2019-02-07 00:58 UTC
A GET https://api.01.unibas.dasch.swiss/admin/users returns all user data, which could be easily abused to gather e-mails and names of users.

I suggest that the API should return a 403 FORBIDDEN in case no auth data is given in the request. Other endpoints may have to be checked as well whether they return data without authentication.

**Comment by subotic** [comment] 2019-02-07 07:19
duplicate of #961

**Closed by subotic** 2019-02-07 07:19 UTC
Labels: API admin, bug

**Comment by subotic** [comment] 2019-02-07 07:22
But thanks for reminding me.

**Comment by andreas-aeschlimann** [comment] 2019-02-07 13:38
Ah, didn't see it. Great!
