### ISSUE TITLE
memory leak in test file

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Knora#386] opened 2017-01-24 12:59 UTC
by running webapi via an IDE, intelliJ, I get the following errors

Warning:scalac: java.lang.OutOfMemoryError: Java heap space
Error:scalac: Error while emitting org/knora/webapi/responders/v1/ResourcesResponderV1SpecContextData$
Java heap space

increasing the maximum heap size of JVM by factor of 100 doesn't solve the problem either (setting Maximum heap size  to 76800!!!) 
Probably there is a memory leak in the file ResourcesResponderV1SpecContextData.

**Comment by tobiasschweizer** [comment] 2017-01-24 13:01
duplicate of https://github.com/dhlab-basel/Knora/issues/349

**Comment by subotic** [comment] 2017-01-24 14:17
``ResourcesResponderV1SpecContextData`` is very large, as it is a dump of response messages. You need to increase the memory of the JVM. Running everything inside SBT works if SBT is started with 2GB of memory.

``export SBT_OPTS="-Xms2048M -Xmx2048M -Xss6M"``

**Comment by subotic** [comment] 2017-01-25 12:51
@SepidehAlassi is this solved?

**Closed** 2017-01-31 17:04 UTC
