### ISSUE TITLE
Minimal user's informations

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1220] opened 2019-02-20 11:20 UTC
Due to PR #1208, it seems to me that we don't have any more informations about any user.
Is there a way to get the username/givenName/familyName from a user's IRI (`knora-api:attachedToUser`) to simply print out in a UI who is the  Resource creator for example?

Maybe related to #1214 ? (probably same use case, nice to have the history but without minimal informations about users, doesn't make sense for UI)

n.b. : we can still display user's name in Salsah by using the v1 API on value which returns `valuecreatorname` and `valuecreator`.

**Comment by benjamingeer** [comment] 2019-02-20 21:16
Have you checked the docs at https://github.com/dhlab-basel/Knora/blob/develop/docs/src/paradox/03-apis/api-admin/users.md ?

It looks like this is the relevant route:

`GET: /admin/users/[iri | email | username]/<identifier>` : return single user identified by [IRI | email | username]

Don’t know what you mean about #1214, that PR hasn’t been merged yet.

**Comment by benjamingeer** [comment] 2019-02-20 21:20
Oh, I guess I understand:

> nice to have the history but without minimal informations about users, doesn't make sense for UI

Do you mean that the version history should include the real name of the user who made each change? That’s not going to happen, because:

1. You have the user IRI, so you can get their real name from the admin interface.
2. It would make the version history response a lot bigger to include it.
3. There are use cases where you don’t need the user information at all, e.g. to display a timeline.

**Comment by subotic** [comment] 2019-02-21 08:00
@benjamingeer The user's information is since #1208 not available freely anymore. Only the user itself or a SystemAdmin can get information about the user.

But we indeed need a minimal set of user information, which should be always returned.

I guess that givenName/familyName are fine. About the `username` I'm not so sure, because it is part of the user's login credentials.

**Comment by benjamingeer** [comment] 2019-02-21 08:07
I think the user’s real name and email address should be available to anyone, because I think a common use case will be that you need to email someone to ask them about their data (“what does this mean?”, “why did you change this?”, etc.). Reusing data often means asking the author about it.

**Comment by subotic** [comment] 2019-02-21 08:26
To implement this, I will need to add a new route, because of the `UserADM` object, which does not allow certain fields to be empty.

Anyway, the rout would be something like:

```
GET /admin/users/iri/[userIRI]/MinimalUserInformation
```

So the fields are:

- `givenName`
- `familiName`
- `email`

I'm not so sure about this. What about user privacy? I wouldn't want that everybody can get my email.

**Comment by subotic** [comment] 2019-02-21 08:37
Shouldn't the user have the final say? It's his information. We could provide a mechanism for contacting other users, without giving out their contact information.

**Comment by gfoo** [comment] 2019-02-21 08:47
In my use case, I just need `givenName/familyName`, about the `email` I'm not sure that from long term point of vue it is a valid information?

**Comment by benjamingeer** [comment] 2019-02-21 09:04
@subotic 

> I wouldn't want that everybody can get my email.

Your work email and telephone number are on the DHLab web site.

> We could provide a mechanism for contacting other users, without giving out their contact information.

We could, but in the meantime, academics’ email addresses are always public. If you don’t mean to share any data, why use Knora? And if you share data, I think you have to expect that people will need to contact you about it. For example, “We’re unable to reproduce your analysis, would you like to talk about it with us before we publish an article about this?”

@gfoo 

> I'm not sure that from long term point of vue it is a valid information?

No contact information is valid forever. But having possibly outdated contact information is better than having no contact information at all.

**Comment by mrivoal** [comment] 2019-02-21 09:11
> I think the user’s real name and email address should be available to anyone, because I think a common use case will be that you need to email someone to ask them about their data (“what does this mean?”, “why did you change this?”, etc.). Reusing data often means asking the author about it.

I think the user's real name to should be available, just like it is right now if you mouse over a value in Salsah 1.5.

As for the email, I would rather advocate against (because we will have to explicitly ask every user to disclose this information and it will raise an unnecessary difficulty/administrative step). Besides, we should bear in mind that there will be a landing page for each project and amongst the metadata should be a valid contact information: probably the PI email that will want to be the first contact point for people interested with the data of a project.

**Comment by benjamingeer** [comment] 2019-02-21 09:19
> As for the email, I would rather advocate against (because we will have to explicitly ask every user to disclose this information

Why would you need to ask? Don’t all your users already have their email addresses displayed publicly on their university web site? Isn’t this this actually obligatory for everyone who works at a university? I’ve worked at four different universities and nobody ever asked me whether I wanted to make my work email address public. It was always published automatically on the university web site. Being contactable is part of being a researcher.

> we should bear in mind that there will be a landing page for each project and amongst the metadata should be a valid contact information: probably the PI email that will want to be the first contact point for people interested with the data of a project.

If there are 20 researchers working on a project, and one of them writes an annotation that says, “I interpret this manuscript to mean XYZ”, and I want to ask the researcher about that, I’m going to be very annoyed if I have to first contact the PI to ask them to put me in touch with the researcher. In fact, if I have the researcher’s name, I will just Google to find their email address on their university web site, but at the same time, I will curse Knora for forcing me to do that.

And what if a large number of people are collaborating on a project, and they often need to contact *each other* about the data they’re working on?

**Comment by mrivoal** [comment] 2019-02-21 09:47
> Don’t all your users already have their email addresses displayed publicly on their university web site?

Actually, yes. But users do not necessarily give their official email (even though we could enforce them to do so, but pfff.). Besides, the DaSCH is not their employer so I wonder if we even have the right to display this information without asking them (RGPD?). Actually, it seems to me that you are always asked if you want to allow a website to display information such as email publicly.

> And what if a large number of people are collaborating on a project, and they often need to contact _each other_ about the data they’re working on?

This case is a bit different. As project member, they might be able to access each other contact information within the admin interface. At least, that is the way I see it.

**Comment by benjamingeer** [comment] 2019-02-21 10:09
OK. I really don’t think we want to make a webmail or chat system within Knora right now. I’ve worked on such systems before, they’re a lot of work to develop. So for now at least, we need to rely on email to allow researchers to be contacted about their data.

So how about three per-user options:

1. User allows their name and contact information to be displayed publicly.
2. User allows this information to be displayed only to members of the projects that the user belongs to.
3. User does not allow this information to be displayed at all, in which case we display the project contact information instead.

With options (2) and (3), the user interface would just have to display a message like “User information hidden, please contact the project administrator.” Keep in mind that this option will make a lot more work for the project admin, who will get a lot of annoying emails like, “Hello, could you please put me in touch with user http://rdfh.ch/users/04fsdfw03948fh who wrote this annotation...”

**Comment by subotic** [comment] 2019-02-21 11:58
```
GET /admin/users/iri/[userIRI]/MinimalUserInformation
```

is then better called:
```
GET /admin/users/iri/[userIRI]/PublicUserInformation
```

And the user can then configure what he wants to make public.

@gfoo is this urgent? If so, I can quickly hack something together and make this route return the user's `givenName` and `familyName`.

**Comment by benjamingeer** [comment] 2019-02-21 12:04
> And the user can then configure what he wants to make public.

Sounds good to me. Maybe the GUI could say something like, "Making your work email public will help others contact you about your data."

**Comment by benjamingeer** [comment] 2019-02-21 12:22
@subotic Although, are you sure you want a different route for this? Will you also have to make one called `ProjectMemberVisibleInformation` for the information that's only visible to other project members? Would it be simpler just to have one route, and to display only what the requesting user has permission to see?

**Comment by subotic** [comment] 2019-02-21 12:49
To serve it back on the existing routes, will require some refactoring as the `UserADM` case class contains required/optional properties as defined in `knora-base`. Here I would need to transform `UserADM` into `PublicUserADM` (or something similar), where each property is optional. It is certainly doable, just requires time.

The `PublicUserInformation` route was meant as a quick fix if @gfoo needs something working in the next days.

**Comment by gfoo** [comment] 2019-02-21 12:51
@subotic no problems, we can wait some weeks :)

**Comment by subotic** [comment] 2019-02-21 12:59
@gfoo great, thanks :-)

**Comment by gfoo** [comment] 2019-06-07 08:17
Any plan for this feature?

**Comment by subotic** [comment] 2019-06-07 18:46
Sorry, none at the moment. Also, I'm not sure how to implement it. If the user is allowed to define himself what is public and what not, then this is basically setting permissions on each of the user's properties. This would also require a route for the user to be able to edit those permissions.

I will see if I can make a quick addition so that you can at least get the user's `givenName/familyName`. Would this suffice for now?

**Comment by gfoo** [comment] 2019-06-11 12:18
> I will see if I can make a quick addition so that you can at least get the user's `givenName/familyName`. Would this suffice for now?

yes

**Comment by subotic** [comment] 2019-06-12 06:58
opened a new issue: #1349

**Closed** 2019-06-14 13:15 UTC
Labels: enhancement
