### ISSUE TITLE
Integrating NIE-INE ontologies in the dhlab Knora fork

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Knora#731] opened 2018-02-10 10:33 UTC
Dear dhlab,
we have been developing ontologies for our projects and would like to include them as a git submodule on our repository at your knora  branch. 

Would that be ok? We would like to write some tests to test them as well so when new Knora versions occur we can update the ontologies in a faster manner.

Would that be ok? Which would be the right place for the submodule - folder?

Thank you very much for you suggestion and best regards,
Jan

**Comment by tobiasschweizer** [comment] 2018-02-12 06:42
I was thinking that it is probably not a good idea to have project ontologies or even more standardized ontologies in the Knora git repo. Of course, system ontologies like `knora-base` or the `knora-api` ontologies need to be part of the Knora repo.

On the one hand we have Knora as a system, on the other you can run Knora with your own settings and custom ontologies. We would have to provide some mechanisms to ensure that ontologies are compliant with the system ontologies if changes are introduced.

**Comment by subotic** [comment] 2018-02-12 07:23
Some time ago, we have decided to have two kinds of ontologies inside Knora: *System* and *Project*. The distinction being that System-Ontologies are shared between projects and Project-Ontologies are not. Beeing a System-Ontology brings with it some restrictions, like not be able simply change them in a way that could brake existing projects.

Also, we discussed the possibility of a *Comunity Release Process* (which still needs to be defined) for System-Ontologies.

That beeing said, you need to think about the way in which the NIE-INE ontologies will be used. I supose that in the long-term the NIE-INE ontologies are going to become System-Ontologies. But for the moment, as they are not stable, should be treated as Project-Ontologies.

If you want to add anything to the Knora repository, then (at the moment at least) it needs to be done through a pull-request originating from inside the original Knora repository. At the moment, we don't support pull-requests from forks, because we have some private variables stored inside Travis, and these cannot be accessed from forks. Because of this, Travis tests are not going to be executed, and thus no merging is possible.

The easiest would be for you to create a subfolder inside the `webapi/_test_data` folder called something like `other.v2.nieine`. There you could put all the ontologies and data files. Afterwards, you could create your test specification under the same package name `org.knora.webapi.other.v2.nieine`.

**Comment by subotic** [comment] 2018-02-12 07:44
I would also suggest the following procedure for project specific tests in general:

If in a branch, any project specific tests fail, then one of the project developers should be contacted and tasked to fix the issue. This way, this project will be aware of any problems or data migration needs, before this branch is merged back into `develop`. If the issues are not resolved in a timely maner, then these tests can be set to `ignore`, so that work on this branch is not impeded. Of yourse, if the issue is a minor thing that can be fixed by ourselves, then we should do it, but still need to inform the other party, so that they are aware of any problems.

**Closed** 2019-03-03 22:32 UTC
