### ISSUE TITLE
Load testing

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#741] opened 2018-02-15 13:57 UTC
I could successfully import my data on January 30th. Since the update of the akka version I get this error after a while:

```
webapi [2018-02-15 14:43:27,980] ERROR - KnoraService(akka://webapi) - Unable to run route http://localhost/v1/resources
webapi org.knora.webapi.TriplestoreConnectionException: Failed to connect to triplestore
webapi 	at org.knora.webapi.TriplestoreConnectionException$.apply(Exceptions.scala:237)
webapi 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:540)
webapi 	at org.knora.webapi.store.triplestore.http.HttpTriplestoreConnector$$anonfun$getTriplestoreHttpResponse$7.applyOrElse(HttpTriplestoreConnector.scala:538)
webapi 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
webapi 	at scala.util.Failure.recover(Try.scala:230)
webapi 	at scala.concurrent.Future.$anonfun$recover$1(Future.scala:392)
webapi 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
webapi 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
webapi 	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
webapi 	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
webapi 	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
webapi 	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
webapi 	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
webapi 	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
webapi 	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
webapi 	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
webapi 	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
webapi Caused by: akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
```

It occurs at different times, so it is probably not related to the data itself. 

As a temporary solution, I changed the akka version back and are running the job again.

**Comment by tobiasschweizer** [comment] 2018-02-15 14:48
see https://github.com/akka/akka-http/issues/1461

**Comment by tobiasschweizer** [comment] 2018-02-15 14:50
we should add load tests to Knora (both for reading and updating data)

**Comment by subotic** [comment] 2018-02-15 18:09
on which branch are you?

**Comment by subotic** [comment] 2018-02-15 18:12
or more precise, which version of akka didn't work and which does work?

**Comment by subotic** [comment] 2018-02-15 23:55
or better yet, what steps do I need to take, to be able to reproduce this?

**Comment by tobiasschweizer** [comment] 2018-02-16 11:03
ok, with 

```
  val akkaBase = "2.4.19"
  val akkaHttp = "10.0.9"
```

everything worked fine again!

**Comment by tobiasschweizer** [comment] 2018-02-16 11:17
I was on branch `https://github.com/dhlab-basel/Knora/tree/wip/goldbach_beta_release` using


```
val akkaBase = "2.5.9"
            val akkaHttp = "10.0.11"
```

**Comment by tobiasschweizer** [comment] 2018-02-16 11:18
I think it will be hard to reproduce. Basically you need to keep it busy with huge import job and then after one and a half hours it throws an exception.

**Comment by tobiasschweizer** [comment] 2018-03-01 07:15
@subotic any news on that? I think it is a known Akka issue.

**Comment by subotic** [comment] 2018-03-01 08:40
According to https://github.com/akka/akka-http/issues/1460, something like this should fix it:

```
val f = for {
                  bindingFuture <- Http().bindAndHandle(routes, host, port)
                  waitOnFuture  <- Future.never
           } yield waitOnFuture

 sys.addShutdownHook { 
    // cleanup logic
}
Await.ready(f, Duration.Inf)
```

I will open a PR and add this. Then you could try it out.

**Comment by tobiasschweizer** [comment] 2018-03-01 09:06
@subotic You would have to add that where Knora communicates with the triplestore?

I could surely try it out but it takes about one hour or even more to provoke the error.

**Comment by subotic** [comment] 2018-03-01 09:28
> You would have to add that where Knora communicates with the triplestore?

Now that you mention it. I have added this to the `KnoraService`, but there it won't do much good in this case. Although, `KnoraService` would probably also need something like this.

**Comment by tobiasschweizer** [comment] 2018-03-01 09:29
These things are really hard to test for. Maybe we can provoke it with load tests you added (both reading and writing)?

**Comment by subotic** [comment] 2018-03-01 09:38
That would be my preferred way.

Looking at `HttpTriplestoreConnector` we only have this line

```
// Send the HTTP request.
response <- http.singleRequest(request)
```

that initiates the request. Maybe it is a parameter issue? Or maybe it will work with the newest RC for `akka-http`? The current `develop` has `akka-http - 10.1.0-RC2`

It would be the easiest if we could recreate this in a test.

**Comment by tobiasschweizer** [comment] 2018-03-01 09:55
hm, my scenario is to load a lot of data into Knora. This is not very specific ;-)

**Comment by subotic** [comment] 2018-03-01 11:27
Is there maybe a curl request and data that you can think of? I could then package this into a test.

In your import, are you creating resources sequentially or is there some parallelism involved?

**Comment by tobiasschweizer** [comment] 2018-03-01 16:58
the import is really stupid (as I am myself :-))

it is simply a loop that creates resources one after an other using http://docs.python-requests.org/en/master/

**Comment by tobiasschweizer** [comment] 2018-03-01 17:28
How can I downgrade to 

```
val akkaBase = "2.4.19"
  val akkaHttp = "10.0.9"
```

This used to work fine two weeks ago. Now it is not possible anymore because of other dependencies.

Otherwise the import does not work. I urgently need to get the data in.

**Comment by subotic** [comment] 2018-03-01 23:15
You can downgrade, but you would need to revert changes from this [commit](https://github.com/dhlab-basel/Knora/commit/c7dcc1581c61ae91b90e177edabf3a3ebdd268e0#diff-c659264b70ddaf5817a9cb7080843327) for `SipiResponderV1.scala` and maybe also some other files.

**Comment by tobiasschweizer** [comment] 2018-03-02 07:08
Everything is pink, I simply love software!

It worked with the current settings:

```
            val akkaBase = "2.5.9"
            val akkaHttp = "10.1.0-RC2"
```

However, I got this when entering sbt on branch goldbach beta release:

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* com.github.jsonld-java:jsonld-java:0.11.1 is selected over 0.10.0
[warn] 	    +- org.apache.jena:jena-arq:3.4.0                     (depends on 0.10.0)
[warn] 	    +- org.knora:webapi_2.12:0.1.0-beta                   (depends on 0.10.0)
[warn] 	* com.typesafe.akka:akka-http_2.12:10.1.0-RC2 is selected over {10.0.10, 10.1.0-RC1}
[warn] 	    +- com.typesafe.akka:akka-http-spray-json_2.12:10.1.0-RC2 () (depends on 10.1.0-RC2)
[warn] 	    +- com.typesafe.akka:akka-http-jackson_2.12:10.1.0-RC2 () (depends on 10.1.0-RC2)
[warn] 	    +- com.typesafe.akka:akka-http-xml_2.12:10.1.0-RC2 () (depends on 10.1.0-RC2)
[warn] 	    +- de.heikoseeberger:akka-http-circe_2.12:1.20.0-RC1  (depends on 10.1.0-RC1)
[warn] 	    +- org.knora:webapi_2.12:0.1.0-beta                   (depends on 10.1.0-RC1)
[warn] 	    +- ch.megard:akka-http-cors_2.12:0.2.2                (depends on 10.0.10)
[warn] 	* org.apache.thrift:libthrift:0.9.3 is selected over 0.9.2
[warn] 	    +- org.apache.jena:jena-arq:3.4.0                     (depends on 0.9.3)
[warn] 	    +- com.uber.jaeger:jaeger-thrift:0.21.0               (depends on 0.9.2)
[warn] Run 'evicted' to see detailed eviction warnings
```

**Comment by subotic** [comment] 2018-03-02 09:28
Those warnings are “normal”. Every time I solve one conflict. Two more pop up.

So, the import works with RC2 of `akka-http`?

**Comment by tobiasschweizer** [comment] 2018-03-02 09:49
> So, the import works with RC2 of akka-http?

The import went through, yes. I guess I would have to try it several times to be sure. 

We should set up some load tests together next week.

**Comment by tobiasschweizer** [comment] 2018-03-02 09:51
Maybe we can just run the integration tests two thousand times in a loop. This is basically what my import does.

**Comment by tobiasschweizer** [comment] 2018-03-02 10:15
No, Travis cannot possibly run them.

We should also involve a running Sipi instance so the scenario gets more realistic. Like my import ;-)

**Comment by loicjaouen** [comment] 2018-03-07 10:28
If ever it might help, I just committed some code with the [python knora/sipi wrapper](https://github.com/LaDHUL/KnoraImport) that we use to import projects.

The interesting part is the [error recovery](https://github.com/LaDHUL/KnoraImport/blob/master/knora/api_er.py) part that excuses most of Knora/Sipi hiccups.

**Comment by benjamingeer** [comment] 2018-06-06 08:09
The error message says:

```
akka.http.impl.engine.client.OutgoingConnectionBlueprint$UnexpectedConnectionClosureException: The http server closed the connection unexpectedly before delivering responses for 1 outstanding requests
```

In this case the server is GraphDB. So perhaps this is a bug in GraphDB, which we can't detect with the older version of Akka, because the older version of Akka silently ignored it, while the newer version of Akka reports it correctly by throwing an exception.

**Comment by tobiasschweizer** [comment] 2018-06-06 08:11
I will have to run the import again soon. I will provide the data and scripts I use so we can make a test case.

**Comment by benjamingeer** [comment] 2018-06-06 08:20
This is the open issue for this in akka-http:

https://github.com/akka/akka-http/issues/1459

**Comment by benjamingeer** [comment] 2018-06-06 09:00
@tobiasschweizer If I understand correctly, you had this problem with akka-http 10.0.11. You upgraded to akka-http 10.1.0-RC2 and the problem didn't occur again. We are now on akka-http 10.1.0. Version 10.1.1 is also available.

From the discussion in akka/akka-http#1459, It looks like this problem could have been caused by a [race condition](https://github.com/akka/akka-http/issues/1459#issuecomment-335508862) in the akka-http client connection pool, which was [rewritten for akka-http 10.1.0](https://akka.io/blog/news/2018/03/08/akka-http-10.1.0-released).

So perhaps your issue was in fact fixed in akka-http 10.1.0. But, we definitely need a test case so we can check.

**Comment by tobiasschweizer** [comment] 2018-06-06 09:01
I can make a simple test case in python so we can try to provoke this error.

**Comment by tobiasschweizer** [comment] 2018-07-10 16:10
@subotic I am currently running the import job again. I can provide a test scenario: a python script and some sample files to tests (xml for text and images). Would that be ok?

**Comment by subotic** [comment] 2018-07-11 15:06
I have added the import script based load test to the [knora-tests](https://github.com/dhlab-basel/knora-tests) repository. Opened a separate issue #932 for the unearthed problem. Thanks for the script.

**Closed by subotic** 2018-07-11 15:06 UTC
Labels: bug

**Comment by tobiasschweizer** [comment] 2018-07-11 15:48
@subotic No problem, you are welcome. I am glad that the problem could be reproduced.
