### ISSUE TITLE
Unclear error on bulk import

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1100] opened 2018-12-05 15:14 UTC
Hello,
(using last Knora version with `sbt dockerComposeUp` way)

Using my stress test script mentioned in #1056 I verified that all my images can be imported alone and all in one large bulk to the anything project (setting a timeout = 120 s to be sure).

Then, using our ontology with a large bulk file containing many resources linked to many `Image` but pointing all to the same small file `affiche.jpg`, it works as well.

But, when all `Image` point to their real images (all the previous tested images), I get this unclear error:  

```
$ curl -u reforme1@unil.ch:test -X POST -d @reforme-geneve-test-data-local.xml -H "content-type: text/xml" http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0111
{"status":4,"error":"akka.pattern.AskTimeoutException: Ask timed out on [ActorSelection[Anchor(akka://webapi/), Path(/user/responderManager)]] after [180000 ms]. Message of type [org.knora.webapi.messages.v1.responder.sipimessages.SipiResponderConversionPathRequestV1] was sent by [Actor[akka://webapi/user/responderManager/resourcesV1#297495954]]. A typical reason for `AskTimeoutException` is that the recipient actor didn't send a reply."}
```

- The ontology and the bulk file : [Ref-Gen-Model.zip](https://github.com/dhlab-basel/Knora/files/2649310/Ref-Gen-Model.zip)
- Images : https://drive.switch.ch/index.php/s/Jgr085ZQvOG12Yx

**Comment by mrivoal** [comment] 2018-12-10 09:52
We could really use some help on this matter because we are have to transfer this projet's data by the end of the year... We thought we are very close, but we just can't get the transfer done.

@benjamingeer could you possibly have a look at this?

**Comment by benjamingeer** [comment] 2018-12-10 10:03
I will try this today.

**Comment by mrivoal** [comment] 2018-12-10 10:03
Thank you :)

**Comment by benjamingeer** [comment] 2018-12-10 11:56
Trying this with the Sipi Docker image and running Knora in SBT, I'm getting a different error:

```
{"status":11,"error":"org.knora.webapi.BadRequestException: Sipi returned a non successful HTTP status code 400 Bad Request: Sipi error message: Submitted mimetypes and/or file extension are inconsistent"}
```

The file in question is `chaeg_531.jpg`. I don't know why Sipi thinks it has the wrong MIME type.

**Comment by lrosenth** [comment] 2018-12-10 12:02
I’ll have a look at it tonight. Could You send me the image file per Email, Marion??

Thanks, Lukas

Von meinem iPhone gesendet

Am 10.12.2018 um 12:56 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


Trying this with the Sipi Docker image and running Knora in SBT, I'm getting a different error:

{"status":11,"error":"org.knora.webapi.BadRequestException: Sipi returned a non successful HTTP status code 400 Bad Request: Sipi error message: Submitted mimetypes and/or file extension are inconsistent"}


The file in question is chaeg_531.jpg. I don't know why Sipi thinks it has the wrong MIME type.

**Comment by gfoo** [comment] 2018-12-10 12:03
Did you try to upload it and create a ThingPicture with Salsah ? It works for me.

**Comment by benjamingeer** [comment] 2018-12-10 13:14
It took me a while to realise that the MIME type error was actually a caused by error in the XML import data. The file `reforme-geneve-test-data-local.xml` contains three instances of `mimetype="image/jpeg)"`, which should be `mimetype="image/jpeg"` (there's an extra parentheses).

**Comment by benjamingeer** [comment] 2018-12-10 13:22
Also, Sipi's MIME checking function thinks that `image/jpeg` is not equal to `image/jpg`.

**Comment by benjamingeer** [comment] 2018-12-10 14:33
I'm having trouble with `dockerComposeUp`: #1122

**Comment by gfoo** [comment] 2018-12-10 16:11
It works for me with a timeout 120 seconds, fails with 60 sec.
It fails too with Knora image `dhlabbasel/webapi:v2.1.0`, anyway we are moving to Knora v3.
Thanks for the help and sorry for the unseen stupid errors (-_-)

**Comment by benjamingeer** [comment] 2018-12-10 16:16
No problem! Do you mean it works for you with the Knora `develop` branch and a timeout of 120 seconds? If so, can we close this issue? I'll keep working on #1122/#1081 in any case.

**Comment by gfoo** [comment] 2018-12-10 20:45
yes, you can close the issue.

**Closed** 2018-12-10 21:08 UTC
Labels: blocking, bug, bulk-import
