### ISSUE TITLE
Not able to initialize repository with latest Knora Version

### ISSUE THREAD

**Issue by musicEnfanthen** [dhlab-basel/Knora#1350] opened 2019-06-12 20:27 UTC
Hi all,

when following the README from scratch how to [run the Knora API Server](https://github.com/dhlab-basel/Knora#run-the-knora-api-server) I get the following error message:

```
sbt:knora> webapi /reStart
[info] Compiling 1 Scala source to C:\xxx\fork_Knora\webapi\target\scala-2.12\classes ...
[info] Done compiling.
[info] Application webapi not yet started
[info] Starting application webapi in the background ...
webapi Starting org.knora.webapi.Main.main()
[success] Total time: 3 s, completed 12.06.2019 21:59:14
sbt:knora> webapi [INFO ] [2019-06-12 21:59:17,063] [ApplicationStateActor] InitStartUp ... please wait.
webapi [INFO ] [2019-06-12 21:59:17,067] [ApplicationStateActor] appStateChanged - to state: StartingUp
webapi [INFO ] [2019-06-12 21:59:17,068] [ApplicationStateActor] appStateChanged - to state: WaitingForRepository
webapi [INFO ] [2019-06-12 21:59:17,286] [ApplicationStateActor] checkRepository - status: NotInitialized, message: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [INFO ] [2019-06-12 21:59:17,286] [ApplicationStateActor] Please initialize repository.
webapi [INFO ] [2019-06-12 21:59:22,321] [ApplicationStateActor] checkRepository - status: NotInitialized, message: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [INFO ] [2019-06-12 21:59:22,321] [ApplicationStateActor] Please initialize repository.
webapi [INFO ] [2019-06-12 21:59:27,374] [ApplicationStateActor] checkRepository - status: NotInitialized, message: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [INFO ] [2019-06-12 21:59:27,374] [ApplicationStateActor] Please initialize repository.
webapi [INFO ] [2019-06-12 21:59:32,398] [ApplicationStateActor] checkRepository - status: NotInitialized, message: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
webapi [INFO ] [2019-06-12 21:59:32,399] [ApplicationStateActor] Please initialize repository.
webapi [INFO ] [2019-06-12 21:59:34,711] [Main$(akka://webapi)] KnoraService - Shutting down.
```

I am on the latest `develop` branch and use the the GDBFree Docker Image which initialized successfully. I have also set the javaOptions to use GDBFree:

```
sbt:knora> show webapi / reStart / javaOptions
[info] Updating webapi...
[info] Done updating.
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
[info] * -javaagent:C:\xxx\.ivy2\cache\org.aspectj\aspectjweaver\jars\aspectjweaver-1.9.1.jar
[info] * -Xms1G
[info] * -Xmx1G
[info] * -Dcom.sun.management.jmxremote
[info] * -Dcom.sun.management.jmxremote.port=1617
[info] * -Dcom.sun.management.jmxremote.authenticate=false
[info] * -Dcom.sun.management.jmxremote.ssl=false
[info] * -Dapp.triplestore.dbtype=graphdb-free
[success] Total time: 11 s, completed 12.06.2019 21:58:38
```
Do I miss something else?

**Comment by loicjaouen** [comment] 2019-06-13 05:50
did you run this?
 
```bash
$ ./graphdb-free-docker-init-knora-test.sh
```

**Comment by musicEnfanthen** [comment] 2019-06-13 11:20
Yes, I did. Runs without problems. I can see the "knora-test" repo in the graphdb GUI on localhost:7200.

**Comment by loicjaouen** [comment] 2019-06-13 15:47
you are right, I get the same result

**Comment by musicEnfanthen** [comment] 2019-06-13 19:05
Thanks a lot for your help and confirmation! I see this behaviour also on different devices and different os (mac and win).

I guess it has something to do with the setting of graphdb-free vs. graphdb-se in the options. The `ApplicationStateActor` expects `id: knora-test, sesameType: owlim:MonitorRepository` (graphdb-se) instead of the `graphdb:FreeSailRepository` (graphdb-free). (See also #955 )

@subotic do you have an idea?

**Comment by loicjaouen** [comment] 2019-06-14 06:01
just to get me going, I did:
- run a non free version of graphdb
  ```bash
  docker run --rm -p 7200:7200 dhlabbasel/graphdb:8.5.0-RC.8-se
  ```
  you then have to connect to graphdb GUI a.k.a. workbench and attach a license
- run the script `./graphdb-se-docker-init-knora-test.sh`  
  I usually edit it to scrap out the ontologies and data that take a lot of time to load (and that I don't use)
- re-run the sbt command without the setting of `-Dapp.triplestore.dbtype=graphdb-free`

and it works

**Comment by loicjaouen** [comment] 2019-06-14 06:09
just to be sure, I did it again with `graphdb-free` and I confirm that for some reason `webapi` doesn't detect `knora-test` as eligible to get started.

**Comment by loicjaouen** [comment] 2019-06-14 06:26
the problem is that for `graphdb-free` we define the repository type as `graphdb:FreeSailRepository` and in the `ApplicationStateActor / checkRepository` we check for a repository type being `owlim:MonitorRepository`.

see the diff of `free` versus `se` repository config:

```bash
$ diff graphdb-free-knora-test-repository-config.ttl.tmpl graphdb-se-knora-test-repository-config.ttl.tmpl
11c11
<      rep:repositoryType "graphdb:FreeSailRepository" ;
---
>      rep:repositoryType "owlim:MonitorRepository" ;
13c13
<        sail:sailType "graphdb:FreeSail" ;
---
>        sail:sailType "owlim:Sail" ;
18c18
<        owlim:query-timeout "5" ;
---
>        owlim:query-timeout "30" ;
```

and the error message in the logs:
```
webapi [INFO ] [2019-06-14 08:15:19,390] [ApplicationStateActor] checkRepository - status: NotInitialized, message: None of the available repositories meet our requirements of id: knora-test, sesameType: owlim:MonitorRepository.
```

that lives in the code at:
https://github.com/dhlab-basel/Knora/blob/1845eb1a0caa0441483d28176b84a2a59cfebe3a/webapi/src/main/scala/org/knora/webapi/store/triplestore/http/HttpTriplestoreConnector.scala#L524

so `webapi` skips the repository `knora-test` because it is not `owlim:MonitorRepository`.


@benjamingeer or @subotic how do we fix this? could it be simply fixed by adding the test of expecting `graphdb:FreeSailRepository` in the detection of an eligible repo in the case of `graphdb-free`?

**Comment by subotic** [comment] 2019-06-14 06:31
Thanks for the analysis. I will take a look at it today. This used to work. I don't know what happened.

**Comment by subotic** [comment] 2019-06-14 10:21
@musicEnfanthen Could you maybe try out the `wip/1350-fix-graphdb-free-support` branch and see if it works for you?

I have also added support for GraphDB-Free with `dockerComposeUp`. It is described in `docs/src/paradox/05-internals/development/build-process.md`.

Basically, you need to type the following into the terminal: 
```bash
$ export KNORA_GDB_TYPE=graphdb-free
$ sbt
sbt:Knora> dockerComposeUp
```` 

This should start the whole stack with GraphDB-Free.

**Closed** 2019-06-14 14:15 UTC
Labels: bug

**Comment by musicEnfanthen** [comment] 2019-06-21 11:39
Sorry for the late response. I can confirm that it works now without problems when following the README instructions (with GraphDB-free from docker image and the rest via scripts and sbt commands from inside local Knora repo). I don't even have to set the `javaOptions` to `graphdb=free` since it is self-detecting now (works for both, Mac and Win).

The `dockerComposeUp` doesn't work for me, neither on Mac nor on Win. But I think this is another issue and I will investigate further.

Thanks a lot for your help @loicjaouen and for fixing this issue @subotic !
