### ISSUE TITLE
Error on update of a richtext property with a mapping

### ISSUE THREAD

**Issue by gfoo** [dhlab-basel/Knora#1069] opened 2018-11-21 13:36 UTC
Using the `http://localhost:3333/v2/values` endpoint to update a richtext property with a mapping 
 with for example this body: 
```json
{
    "@id": "http://rdfh.ch/0113/JYIs9DmnR6eUVEf6oZfS0w",
    "@type": "onto:Person",
    "onto:hasBiography": {
        "@id": "http://rdfh.ch/0113/JYIs9DmnR6eUVEf6oZfS0w/values/3AYB5YIgS8ChR2FltUy-Sw",
        "@type": "knora-api:TextValue",
        "knora-api:textValueAsXml": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n    <text>\n    <p>Test</p>\n    </text>",
        "knora-api:textValueHasMapping": {
            "@id": "http://rdfh.ch/standoff/mappings/StandardMapping"
        }
    },
    "@context": {
        "knora-api": "http://api.knora.org/ontology/knora-api/v2#",
        "onto": "http://0.0.0.0:3333/ontology/0113/lumieres-lausanne/v2#"
    }
}
```

I don't understand the following error while, finally, the property is modified in graphdb as expected:
```json
{"error":"org.knora.webapi.AssertionException: The value saved as http://rdfh.ch/0113/JYIs9DmnR6eUVEf6oZfS0w/values/-8KBL68LSfOEP36hj2ZSOw is not the same as the one that was submitted"}
```

**Comment by benjamingeer** [comment] 2018-11-21 13:37
This is a bug: Knora updated the triplestore, then read back the value from the triplestore to check that it was saved correctly, and found that there is some difference between what was saved and what was supposed to be saved.

**Comment by benjamingeer** [comment] 2018-11-21 13:39
Could you give me a complete test case (ontology, admin data, test data including the resource and value to be updated)?

**Comment by benjamingeer** [comment] 2018-11-21 13:40
Or can you reproduce this with the `anything` ontology?

**Comment by gfoo** [comment] 2018-11-21 13:43
yes, with `anything`, I prefer.  I post that this afternoon.

**Comment by gfoo** [comment] 2018-11-21 14:47
well, I cannot reproduce it neither with anything or my ontology using Postman.
I thought it was because of the `Bearer auth` way I use from Angular, but apparently not...
I will keep you informed if I can reproduce it without Angular.

**Comment by benjamingeer** [comment] 2018-11-21 14:52
I suspect a problem with escaping and unescaping the text (it has to be escaped to be included in the SPARQL update). In any case, it has to be a bug in the update code: the update is either being done incorrectly or checked incorrectly. So it would be great to be able to reproduce it somehow.

**Comment by gfoo** [comment] 2018-11-21 15:09
yes, exactly, I'm exploring that, the value put in json come from CKEditor and I have had some issues few days ago because `\n` was replaced by `&nbsp;` (was not accepted by Knora).  I disabled it following this solution: https://stackoverflow.com/questions/9741620/ckeditor-unwanted-nbsp-characters

But there is maybe more things to do to cleanup data before to send it to Knora ? I supposed that Knora have to accept any valid xml string or sthg like that ?

**Comment by gfoo** [comment] 2018-11-21 15:14
I also suspect the way I convert the string coming from CKEditor into a json string by using `JSON.stringify` method : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/JSON/stringify

**Comment by benjamingeer** [comment] 2018-11-21 15:17
> But there is maybe more things to do to cleanup data before to send it to Knora ? I supposed that Knora have to accept any valid xml string or sthg like that ?

Knora should accept any valid XML. But you have to escape the XML to put it in an JSON string. But it looks like you did that. So perhaps you're doing everything correctly, and Knora is doing something incorrectly with escaping and unescaping during/after the update.

**Comment by benjamingeer** [comment] 2018-11-21 15:31
> after few tests, it is clearly related to &nbsp;, I thought it was removed, but apparently not ...

OK, but Knora should still do something reasonable if it gets `&nbsp;`. Now that you know the problem is with &nbsp;, can you make a test case so I can reproduce the issue?

**Comment by gfoo** [comment] 2018-11-21 16:38
so, we have two problems there: 
1.  `&nbsp;` : see #1071
2.  the first error reported in this issue could come from a scenario mixing resource creation (a bulk import) with an admin user, then a modification of a text property with a mapping by an another user (non admin and having permissions to modify properties) -> test case in progress

**Comment by benjamingeer** [comment] 2018-11-21 16:41
OK thanks. I will think about the first one and ask @tobiasschweizer, who is the XML expert. :)

Looking forward to a test case for the second one, because we really have to fix whatever is causing that `AssertionException`.

**Comment by benjamingeer** [comment] 2018-11-22 08:05
There wasn't even a `valueHasQname` in `knora-base` when we first moved the Knora code to GitHub.

**Comment by gfoo** [comment] 2018-11-22 09:21
Finally the bug could come from escaping and not from permissions as I mentioned before.

In my scenario I import data using bulk import and then try to modify a value (generated by CKEditor) using v2 API. So, what happened is that I imported data with escaped chars using bulk import, and then tried to modify a value with v2 API which does not allow escaped chars.

We can import data containing escaped characters like `\n`:
`curl -s -u root@example.com:test -X POST -d @create.xml http://localhost:3333/v1/resources/xmlimport/http%3A%2F%2Frdfh.ch%2Fprojects%2F0001`

```
<?xml version="1.0" encoding="UTF-8"?>
<knoraXmlImport:resources xmlns="http://api.knora.org/ontology/0001/anything/xml-import/v1#" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://api.knora.org/ontology/0001/anything/xml-import/v1# p0001-anything.xsd" xmlns:p0001-anything="http://api.knora.org/ontology/0001/anything/xml-import/v1#" xmlns:knoraXmlImport="http://api.knora.org/ontology/knoraXmlImport/v1#">
<Thing id="testEscape">
  <knoraXmlImport:label>testEscape</knoraXmlImport:label>
  <hasRichtext knoraType="richtext_value" mapping_id="http://rdfh.ch/standoff/mappings/StandardMapping">
     <text xmlns="">
         <p>\n test</p>
       </text>
     </hasRichtext>
</Thing>
</knoraXmlImport:resources>
```

Using the v2 create resource API (or updating a value from preivous bulk created resource), we can't : 
`curl -s -u root@example.com:test -X POST -d @create.json http://localhost:3333/v2/resources`

```
{"error":"org.knora.webapi.AssertionException: Resource <http://rdfh.ch/0001/fhnZX88ZT_-noVHrcIJZFQ> was saved, but one or more of its values are not correct"}
```
```
{
  "@type" : "anything:Thing",
  "anything:hasRichtext" : {
    "@type" : "knora-api:TextValue",
    "knora-api:textValueAsXml" : "<?xml version=\"1.0\" encoding=\"UTF-8\"?><text><p>\n test</p></text>",
    "knora-api:textValueHasMapping" : {
      "@id" : "http://rdfh.ch/standoff/mappings/StandardMapping"
    }
  },
  "knora-api:attachedToProject" : {
    "@id" : "http://rdfh.ch/projects/0001"
  },
  "rdfs:label" : "testEscape",
  "@context" : {
    "rdf" : "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "knora-api" : "http://api.knora.org/ontology/knora-api/v2#",
    "rdfs" : "http://www.w3.org/2000/01/rdf-schema#",
    "xsd" : "http://www.w3.org/2001/XMLSchema#",
    "anything" : "http://0.0.0.0:3333/ontology/0001/anything/v2#"
  }
}
```

**Comment by gfoo** [comment] 2018-11-22 10:19
So the questions are in my case:

1. Bulk xml import accept `\n` chars but are not interpreted as line feed, in Salsah CKEditor we can see the string `\n`, is not normal ? 
Regarding https://en.wikipedia.org/wiki/XML#Escaping, I think that the bulk import is correct, I have to cleanup my data.

2. Can we add escaped chars in json sent to Knora V2 API ?
Because I use `JSON.stringify` , a line feed is replaced by '\n'. Is it a json convention that  Knora should allow ? (I think it is : http://json.org/, so Knora should accept it)

In a browser console : 
```
> val = '\na'
"
a"
> JSON.stringify({"v1": 3, "v2": val})
"{"v1":3,"v2":"\na"}"
```

**Comment by benjamingeer** [comment] 2018-11-22 10:20
Many thanks, this is great! I will try to figure this out this afternoon.

**Comment by benjamingeer** [comment] 2018-11-22 14:48
1. In XML, `\n` has no special meaning (it just represents the two characters `\` and `n`), so I think it's correct that it's not interpreted as a line feed in the bulk import, and that you then see `\n` in CKEditor. You could use `&#10;` in XML to represent a newline, but you can also just put a real newline character in the XML document.
2. The JSON-LD that you're sending to API v2 with `\n` is correct, because here you have XML embedded in a JSON string, and `\n` does represent a line feed in JSON.

The bug happens because of this: Knora is saving the text correctly in the triplestore, but when it reads the value back to check that it was saved correctly, the comparison is done wrong. I'm working on a fix.

**Comment by benjamingeer** [comment] 2018-11-23 08:56
@gfoo I have been able to reproduce the problem with `\n` when creating a resource via API v2, but not when updating an existing value. Could you please double-check and see if you have a test case that produces an error when updating a value?

PR #1074 fixes the error when creating a resource. Could you test branch `fix/1069-fix-update-check` and confirm that it works for you?

**Comment by gfoo** [comment] 2018-11-23 08:57
ok, I will do that this morning.

**Comment by gfoo** [comment] 2018-11-23 10:19
You indeed fixed the create test case but not the update.
I try to provide you a test case.

**Comment by benjamingeer** [comment] 2018-11-23 10:21
I have a test case for the update here:

https://github.com/dhlab-basel/Knora/pull/1074/files#diff-76b09ec70455ab4fddbf87a2b4ab34ce

You just have to replace `VALUE_IRI` with the IRI of the value to be updated.

**Comment by benjamingeer** [comment] 2018-11-23 10:21
But it works for me.

**Comment by gfoo** [comment] 2018-11-23 10:48
Your anything test case works for me 👍 
But the following data coming from CKEditor still produces the same error (don't know what I have to cleanup there ? '\"' ? '<' not escaped ? )  : 
```
<?xml version=\"1.0\" encoding=\"UTF-8\"?><text><p>S. <strong>entretient</strong> une <strong>correspondande</strong> avec Victor de Ruiqueti, marquis de Mirabeau.\"Mirabeau et Sacconay se seraient rencontrés à l’Académie militaire de Paris au tournant des années 1730. Leur amitié se scelle durant l’hiver 1732-1733, lorsque Mirabeau, étant tombé malade en garnison dans les environs de Strasbourg, se réfugie chez la famille de Sacconay à Bursinel et y passe le temps de sa convalescence. Au cours de ce séjour, Mirabeau renforce son amitié avec Sacconay et s’attache à sa famille. Il témoigne souvent de son affection particulière pour cet ami suisse, que ce soit dans les lettres qu’il lui adresse ou dans ses échanges avec d’autres correspondants. Ainsi, une lettre de Mirabeau à son frère, écrite le 1er avril 1788, révèle la profondeur de leur amitié : « En apparence, entièrement hétérogènes de caractère, nous nous aimions depuis cinquante-sept ans de l’amitié la plus tendre et la plus confiante, de la même manière dont on s’aime à seize ans, avant d’avoir été détérioré par l’usage du monde et par sa propre aridité. Notre correspondance la plus exacte n’avait jamais été interrompue ». Et de fait, la dernière lettre de Mirabeau date d’à peine trois mois avant la mort de Sacconay, survenue le 15 mars 1788.\"(source: extrait tiré de Lumières.Lausanne, projet \"<a href=\"http://lumieres.unil.ch/projets/mirabeau\">Correspondance Mirabeau - Sacconay (1731-1784)</a>\", Université de Lausanne, consulté le 23.01.2017)</p></text>
```

**Comment by gfoo** [comment] 2018-11-23 10:52
tested `\\"` and it works ...

**Comment by benjamingeer** [comment] 2018-11-23 10:56
Very interesting! Trying to figure this out now.

**Comment by gfoo** [comment] 2018-11-23 10:57
it probably comes from this part : `<a href=\"http://lumieres.unil.ch/projets/mirabeau\">`

is there a rule for URL of `<a>`standoff tag ?

**Comment by gfoo** [comment] 2018-11-23 11:01
https://docs.knora.org/paradox/03-apis/api-v1/xml-to-standoff-mapping.html#the-knora-standard-mapping: URL should be an IRI ? 

> knora-base:StandoffUriTag: Represents a reference to a URI (the URI of the target resource must be submitted in the data type attribute).

**Comment by gfoo** [comment] 2018-11-23 11:15
I noticed that in the bulk import doc we don't have to provide a xml header `<?xml version=\"1.0\" encoding=\"UTF-8\"?>` while it is required in the v2 API, is it normal ?

**Comment by benjamingeer** [comment] 2018-11-23 11:17
`<a>` is `knora-base:StandoffUriTag` and should accept any URL. And if the standoff processing code didn't like your URL, you'd get an error message specifically about that.

In this case, the text is matching, so it's not a problem with escaping. However, there is indeed something going wrong with the processing of the `StandoffUriTag`. Trying to figure this out now...

> I noticed that in the bulk import doc we don't have to provide a xml header

You mean for a text value? Yes, it's normal, because you provide it at the top of the whole bulk import XML document. The XML for the text value isn't a separate document, it's just more tags in the same document.

**Comment by benjamingeer** [comment] 2018-11-23 12:47
The bug in processing the link is because of a one-character typo:

https://github.com/dhlab-basel/Knora/pull/1074/files#diff-98574063df2c49f2eb1475633d81e150L753

@gfoo Can you try again with the `fix/1069-fix-update-check` branch?

@tobiasschweizer `StandoffTagUtilV2` was constructing this:

```scala
StandoffTagIriAttributeV2(http://www.knora.org/ontology/knora-base#valueHasUri,http://www.google.ch,true)
```

instead of this:

```scala
StandoffTagUriAttributeV2(http://www.knora.org/ontology/knora-base#valueHasUri,http://www.google.ch)
```

So we had the wrong attribute class containing the right standoff property IRI. This didn't matter in API v1 because:

* When API v1 checks an updated value, it only checks that the value exists in the triplestore; it doesn't check the value's content.
* The conversion of standoff to XML just looked at the standoff property IRI, `http://www.knora.org/ontology/knora-base#valueHasUri`, which was correct, so the generated XML was correct (I added some more checks to `ResourcesV1R2RSpec` in #1074 to verify this).

It matters in API v2 because API v2 checks the content of the updated value, so the standoff attribute object is checked, too.

**Comment by tobiasschweizer** [comment] 2018-11-23 12:50
@benjamingeer this was the chance of your life to make a PR that has just one commit with one changed file with with one character changed :-)

just joking ... Great that you found out what went wrong and added more tests, thx.

**Comment by gfoo** [comment] 2018-11-23 12:59
oh yeah, it works !
Proooooudly tested ;-) with my [bash/python/curl/jq/sed  testbed for ever](https://gist.github.com/gfoo/74b55f44b3b55b1a8931884f5ccd7365)  ☠️

**Comment by benjamingeer** [comment] 2018-11-23 13:00
@gfoo Thanks very much for the great bug report!

**Closed** 2018-11-26 14:18 UTC
Labels: API v2, bug
