### ISSUE TITLE
Float Value is not correct when converted from JSON to case class

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Knora#152] opened 2016-05-26 08:32 UTC
When creating or modifying a float value, Knora creates a wrong floating number.

For example, if you submit 

```
float_value:5.6
```

Knora creates `5.599999904632568`

Probably this happens when Knora route parses the json into a case class (`ValuesRouteV1` -> Post and Put, `ResourcesRouteV1` -> Post)

**Comment by benjamingeer** [comment] 2016-05-26 08:59
This might help: http://floating-point-gui.de/

**Comment by loicjaouen** [comment] 2016-05-26 09:21
it is not wrong, it is a valid float representation of 5.6, according to the expected behaviour, we might want [arbitrary precision storage](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html) for decimal numbers or arbitrary precision formatting of float on the output of float `format("%.6f",` float_value)`.

**Comment by subotic** [comment] 2016-05-26 10:54
An answer on how to override JsonFormat[Float] in spray-json:
https://groups.google.com/forum/?pli=1#!topic/spray-user/HjdQzXzxUcw

The question is, how many decimals do we need? I could add an implicit extension, so that in the converted JSON we then have a rounded number.

**Comment by loicjaouen** [comment] 2016-05-26 13:40
I would say, keep the string from start to end.

Unless decimal numbers have a semantic meaning to knora, keep the string.
If it has a semantic meaning (because knora computes averages and makes stats) then leave to the user the choice of the representation that makes sense (float, double, bignum).

Formatting on decimal precision won't help because it is not about decimals but significant digits.
The float is 32b used in 1 but for sign, 23 for significant, 8 for exponent.
So the significant bits can code up to 2^23 figures, that's 8388608 which is a 7 digit number.
If you keep the scientific notation, you'll be fine with a formatting rule at the 6th decimal.

Now if 5.6 turns into 5.5999999 then 56000000 can turn into 55999999 and formatting the decimals won't help.

**Comment by benjamingeer** [comment] 2016-06-07 15:03
The basic problem here is that there is no exact binary representation of the decimal number 5.6. You can see this if you convert a `float` to a `BigDecimal`, which has arbitrary precision:

```
scala> val b = new BigDecimal(5.6f)
b: java.math.BigDecimal = 5.599999904632568359375
```

What you're seeing here is the actual value represented by the Scala (or Java) `float`.  If you have a `float` and just convert it to a string, it is automatically rounded according to the IEEE 754 rules for floating-point arithmetic:

```
scala> val f = 5.6f
f: Float = 5.6
```

So when you just use `float`, its inherent imprecision is simply hidden from you.

The spray-json library represents a JSON number as a `BigDecimal` in [JsNumber](https://github.com/spray/spray-json/blob/master/src/main/scala/spray/json/JsValue.scala). So if you give spray-json the `float` approximation of 5.6, you get the more precise representation provided by `BigDecimal`.

`BigDecimal` can represent the exact value 5.6, but only if you initialise it with a string rather than with a `float`:

```
scala> val b = new BigDecimal("5.6")
b: java.math.BigDecimal = 5.6
```

We can't store floating-point numbers as strings in the triplestore, because we need to be able to write SPARQL queries that search for numbers (e.g. using the `<` and `>` operators).

I think the best option would be to use arbitrary precision storage as Loïc suggested. RDF has the type [xsd:decimal](https://www.w3.org/TR/xmlschema11-2/#decimal), which offers arbitrary precision, like `BigDecimal`. I suggest we switch from `xsd:float` to `xsd:decimal` in `knora-base`, rename `FloatValue` to `DecimalValue`, and always use `BigDecimal` rather than `float` in Scala. Then I think 5.6 would always be 5.6.

**Comment by benjamingeer** [comment] 2016-06-08 13:42
This should be fixed now on the `wip/test_ontology` branch.

**Closed** 2016-07-25 15:54 UTC
Labels: bug
